default: &default
  adapter: postgresql
  encoding: unicode
  pool:    <%= ENV.fetch("RAILS_MAX_THREADS", 10) %>
  host:     <%= ENV.fetch("DB_HOST") %>
  port:     <%= ENV.fetch("DB_PORT") %>
  username: <%= ENV.fetch("DB_USER") %>
  password: <%= ENV.fetch("DB_PASS") %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "invoix_development") %>
  sslmode: disable

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "backend_test") %>
  sslmode: disable

staging:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "backend_staging") %>
  sslmode: require

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "defaultdb") %>
  sslmode: require
